
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 04 23:06:39 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 45;
  public static final int INCREMENT = 37;
  public static final int CONST = 9;
  public static final int GREATEROREQUAL = 32;
  public static final int DEVIDE = 29;
  public static final int NOTEQUAL = 31;
  public static final int GREATER = 50;
  public static final int LPAREN = 43;
  public static final int SEMI = 39;
  public static final int CONTINUE = 16;
  public static final int LESS = 49;
  public static final int DECREMENT = 38;
  public static final int MINUS = 27;
  public static final int RPAREN = 44;
  public static final int CHARACTER = 24;
  public static final int AND = 34;
  public static final int RECORD = 20;
  public static final int OR = 35;
  public static final int COMMA = 42;
  public static final int CLASS = 6;
  public static final int EQUALEQUAL = 30;
  public static final int LESSOREQUAL = 33;
  public static final int PLUS = 26;
  public static final int MULTIPLY = 28;
  public static final int IF = 10;
  public static final int THIS = 17;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int BOOLEAN = 23;
  public static final int RETURN = 4;
  public static final int RBRACKET = 46;
  public static final int EQUAL = 36;
  public static final int SUPER = 18;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int NUMBER = 22;
  public static final int BREAK = 5;
  public static final int IDENT = 25;
  public static final int VOID = 21;
  public static final int COLON = 40;
  public static final int LBRACE = 47;
  public static final int ELSE = 8;
  public static final int ENUM = 7;
  public static final int READ = 14;
  public static final int GOTO = 19;
  public static final int WHILE = 12;
  public static final int RBRACE = 48;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int PRINT = 3;
  public static final int DO = 11;
}

